{"name": "test_001[5-6]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (5 + 6) == 3", "trace": "x = 5, y = 6\n\n    @pytest.mark.parametrize('x,y',[(1,2),(3,4),(5,6)])\n    def test_001(x,y):\n>       assert x+y == 3\nE       assert (5 + 6) == 3\n\ntest_01.py:17: AssertionError"}, "parameters": [{"name": "x", "value": "5"}, {"name": "y", "value": "6"}], "start": 1593164089180, "stop": 1593164089181, "uuid": "cbdf2bcd-a542-42f0-b40c-89208ff49e95", "historyId": "5908a2163d015d676b4329c29a3b532a", "testCaseId": "02922ae489eea352004b3a4d71e86ce3", "fullName": "test_01#test_001", "labels": [{"name": "suite", "value": "test_01"}, {"name": "host", "value": "DESKTOP-GQJA6VO"}, {"name": "thread", "value": "13644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}